### ISSUE TITLE
getv --as-json flag non-functional on strings.

### ISSUE THREAD

**Issue by yoshiya8** [pastdev/clconf#15]
## Description
When I use `getv --as-json` to extract a string value, I get the actual string rather than a JSON string.

## How to repeat
```bash
clconf \
  --ignore-env \
  getv \
  --yaml-base64 "$(echo 'item: Book "Binder"' | base64 --wrap=0)" \
  "/item" \
  --as-json
```
Expected result:
```
"Book \"Binder\""
```
Actual result:
```
Book "Binder"
```

**Comment by lucastheisen** [comment]
[Fixed](https://github.com/pastdev/clconf/commit/6aa80ba41c933fe1b646099be0ee6155230ff9fa)
