### ISSUE TITLE
Template command does not generate empty output 

### ISSUE THREAD

**Issue by yoshiya8** [pastdev/clconf#27]
# Problem

`template` command does not generate an ouput when that output file would be empty.

## How to reproduce

Using the following two files, issue the command:
```bash
clconf template --yaml values.yml --in-place template.clconf
```

### `values.yml`
```yaml
---
my_array: []
```

### `template.clconf`
```
{{- if gt (len (ls "/my_array")) 0 -}}
Lots
of
stuff
{{ end -}}
```

## Expected results
An empty file: `template`

## Actual results
No file generated

## Workarounds
If the output file accepts comments, we can put a boilerplate comment in the template - but this only works for certain use-cases.

## Resolution
None yet.

**Comment by lucastheisen** [comment]
This is actually a _feature_ allowing for templated files to not be created if they wouldn't have content.  You can change the behavior using `--keep-empty`:

```console
ltheisen@PC:~$ rm -rf /tmp/outdir; clconf --yaml <(echo "my_array: []") template --keep-empty <(printf '{{if gt (len (ls "/my_array")) 0}}stuff{{end}}') /tmp/outdir; ls -al /tmp/outdir
Templated: "/dev/fd/62" => "/tmp/outdir/62"
total 0
drwxrwxr-x 1 ltheisen ltheisen 4096 Mar  8 18:05 .
drwxrwxrwt 1 root     root     4096 Mar  8 18:05 ..
-rw------- 1 ltheisen ltheisen    0 Mar  8 18:05 62
```
