### ISSUE TITLE
lsdir template func sorts keys in lexicographical order

### ISSUE THREAD

**Issue by cvirtucio** [pastdev/clconf#36]
Hi, the [`lsdir` func](https://github.com/pastdev/clconf/blob/65de9219606a3aa771eb4b6eba505df5a21347c3/pkg/memkv/store.go#L28) currently sorts numerical keys in lexicographical order:

```
clconf --yaml /tmp/foo.yml getv --template-string '{{ range $idx := lsdir "/foo" }}
{{- $idx }}
{{ end }}
'
0
1
10
11
12
13
14
15
16
17
18
19
2
20
21
22
23
24
25
26
27
28
29
3
30
4
5
6
7
8
```

This is due to the `sort.Strings()` call [here](https://github.com/pastdev/clconf/blob/65de9219606a3aa771eb4b6eba505df5a21347c3/pkg/memkv/store.go#L147) call. I realize that this is part of `clconf` 's core, but is there any chance of [natural sort](https://en.wikipedia.org/wiki/Natural_sort_order) in some form in the future?

**Comment by lucastheisen** [comment]
Any reason not to use [sort](https://github.com/pastdev/clconf/blob/65de9219606a3aa771eb4b6eba505df5a21347c3/docs/templates.md#sort):

```console
(mitre-wsl-rocky9) ltheisen@MM269697-PC ~/git/caasd-portal-test-new
$ clconf --pipe getv --template-string '{{range $i := sort (lsdir "/") "int"}}{{$i}}{{"\n"}}{{end}}' <<'EOF'
- one: item
- two: item
- three: item
- four: item
- five: item
- six: item
- seven: item
- eight: item
- nine: item
- ten: item
- eleven: item
- twelve: item
EOF
0
1
2
3
4
5
6
7
8
9
10
11
```

**Comment by cvirtucio** [comment]
yup, that approach works for us.
