### ISSUE TITLE
clconf example doesn't match definition

### ISSUE THREAD

**Issue by ristonj** [pastdev/clconf#43]
In the configuration section, the example doesn't match the documentation.

>  Using clconf requires one or more yaml files (or strings) to merge together. They are specified using either using environment variables or command line options, as either files or base64 encoded strings. The order they are processed in is as follows:
> 
```
     --yaml: One or more files.
    YAML_FILES environment variable: A comma separated list of files.
    --yaml-base64: One or more base64 encoded strings containing yaml.
     YAML_VARS environment variable: A comma separated list of environment variable names, each a base64 encoded string 
 containing yaml.
    --stdin: One or more --- separated yaml files read from stdin.
    --var: One or more path overrides of the form /foo="bar". Key is a path, an value is json/yaml encoded.
     --patch: One or more rfc 6902 json/yaml patch files to apply to the result of merging all the config sources.
     --patch-string: One or more rfc 6902 json/yaml patches to apply to the result of merging all the config sources.
```
> 
> All of these categories of input will be appended to each other and the last defined value of any key will take precedence. For example:
``` 
 YAML_FILES="a.yml,b.yml"
 YAML_VARS="C_YML_B64,D_YML_B64"
 C_YML_B64"$(echo -e "c:\n  foo: bar" | base64 -w 0)
 D_YML_B64"$(echo -e "d:\n  foo: bar" | base64 -w 0)
 
 G_YML_B64="$(echo -e "g:\n  foo: bar" | base64 -w 0)
 H_YML_B64="$(echo -e "h:\n  foo: bar" | base64 -w 0)
 
 clconf \
   --yaml e.yml \
   --yaml f.yml \
   --yaml-base64 "$G_YML_B64" \
   --yaml-base64 "$H_YML_B64" \
   --var '/foo="bar"' \
   --patch patch.json \
   --patch-string '[{"op": "replace", "path": "/foo", "value": "baz"}]' \
   <<<"---\nfoo: baz"
``` 
> Would be processed in the following order:
> 
>     a.yml
>     b.yml
>     C_YML_B64
>     D_YML_B64
>     e.yml
>     f.yml
>     G_YML_B64
>     H_YML_B64
>     stdin
>     `/foo="bar"`
>     patch.json
>     `[{"op": "replace", "path": "/foo", "value": "baz"}]`

The documentation is correct, the example is incorrect.

**Comment by lucastheisen** [comment]
Resolved by #44
